'use client';

import { useState, FormEvent, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Calculator, Sparkles, BarChart3, ArrowRight, Search,
  TrendingUp, Layers, Database, Shield, Gauge,
} from 'lucide-react';
import { Header } from '@/components/Header';
import { cn } from '@/lib/utils';

const POPULAR = [
  { symbol: 'AAPL',  name: 'Apple'      },
  { symbol: 'MSFT',  name: 'Microsoft'  },
  { symbol: 'GOOGL', name: 'Alphabet'   },
  { symbol: 'NVDA',  name: 'NVIDIA'     },
  { symbol: 'TSLA',  name: 'Tesla'      },
  { symbol: 'AMZN',  name: 'Amazon'     },
  { symbol: 'META',  name: 'Meta'       },
  { symbol: 'V',     name: 'Visa'       },
];

const FEATURES = [
  {
    icon: BarChart3,
    title: 'Full Dashboard',
    desc: '5-year financial trends, 30+ ratios, DCF summary, Altman Z-Score',
    href: '/dashboard',
    badge: 'Overview',
  },
  {
    icon: Calculator,
    title: 'DCF Valuation',
    desc: 'Interactive intrinsic value calculator with real-time sensitivity matrix',
    href: '/valuation',
    badge: 'Interactive',
  },
  {
    icon: Sparkles,
    title: 'AI Equity Research',
    desc: 'Comprehensive analyst-grade report generated by GPT-4o in seconds',
    href: '/ai-analysis',
    badge: 'AI-powered',
  },
];

const STATS = [
  { label: 'Financial Ratios', value: '30+' },
  { label: 'Years of Data',    value: '5Y'  },
  { label: 'Analysis Engines', value: '3'   },
  { label: 'Markets Covered',  value: 'US Stocks' },
];

export default function LandingPage() {
  const router = useRouter();
  const [symbol, setSymbol] = useState('');
  const [focused, setFocused] = useState(false);

  const handleSubmit = (e?: FormEvent) => {
    e?.preventDefault();
    const s = symbol.trim().toUpperCase();
    if (!s) return;
    router.push(`/dashboard?symbol=${s}`);
  };

  const handleQuickPick = (s: string) => {
    router.push(`/dashboard?symbol=${s}`);
  };

  return (
    <div className="relative min-h-screen overflow-hidden">
      {/* Decorative backgrounds */}
      <div className="fixed inset-0 grid-bg pointer-events-none opacity-40" />
      <div className="fixed top-0 left-1/2 -translate-x-1/2 w-[90vw] h-[60vh] bg-radial-glow pointer-events-none" />

      {/* Animated floating orbs */}
      <motion.div
        className="fixed top-20 right-[10%] w-64 h-64 rounded-full pointer-events-none"
        style={{ background: 'radial-gradient(circle, rgba(212,165,116,0.15) 0%, transparent 70%)' }}
        animate={{ y: [0, 30, 0], opacity: [0.5, 0.8, 0.5] }}
        transition={{ duration: 8, repeat: Infinity, ease: 'easeInOut' }}
      />
      <motion.div
        className="fixed bottom-40 left-[5%] w-96 h-96 rounded-full pointer-events-none"
        style={{ background: 'radial-gradient(circle, rgba(212,165,116,0.08) 0%, transparent 70%)' }}
        animate={{ y: [0, -40, 0], opacity: [0.3, 0.6, 0.3] }}
        transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
      />

      <Header />

      <main className="relative">
        {/* ════════════════════════════════════════════════
            HERO — Main ticker entry
        ════════════════════════════════════════════════ */}
        <section className="max-w-6xl mx-auto px-6 pt-20 md:pt-32 pb-20 relative">
          {/* Small eyebrow tag */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="flex justify-center mb-8"
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full glass">
              <div className="w-1.5 h-1.5 rounded-full bg-[var(--positive)] animate-pulse" />
              <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-[var(--text-secondary)]">
                Institutional Intelligence · Est. 2026
              </span>
            </div>
          </motion.div>

          {/* Main headline */}
          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
            className="font-display text-center font-light tracking-tighter leading-[0.95] mb-8"
          >
            <span className="block text-6xl md:text-8xl lg:text-9xl text-[var(--text-primary)]">
              The art of
            </span>
            <span className="block text-6xl md:text-8xl lg:text-9xl text-gold italic mt-1">
              equity research.
            </span>
          </motion.h1>

          {/* Subheadline */}
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            className="text-center text-lg md:text-xl text-[var(--text-secondary)] max-w-2xl mx-auto text-balance leading-relaxed mb-14"
          >
            Institutional-grade financial analysis, <em className="text-[var(--accent)] not-italic">reimagined</em>.
            Enter a ticker to begin — unlock DCF valuation, AI-written research,
            and deep financial intelligence in one elegant interface.
          </motion.p>

          {/* Hero ticker input */}
          <motion.form
            onSubmit={handleSubmit}
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4, ease: [0.16, 1, 0.3, 1] }}
            className="max-w-2xl mx-auto relative"
          >
            <div
              className={cn(
                'relative transition-all duration-500',
                focused && 'scale-[1.02]'
              )}
            >
              {/* Glow effect */}
              <div
                className={cn(
                  'absolute -inset-2 bg-gold-gradient rounded-full blur-xl transition-opacity duration-500',
                  focused ? 'opacity-40' : 'opacity-20'
                )}
              />

              <div className="relative glass rounded-full flex items-center p-2">
                <div className="pl-6 pr-3 flex items-center">
                  <Search size={20} className="text-[var(--accent)]" strokeWidth={1.5} />
                </div>
                <input
                  type="text"
                  value={symbol}
                  onChange={(e) => setSymbol(e.target.value.toUpperCase())}
                  onFocus={() => setFocused(true)}
                  onBlur={() => setFocused(false)}
                  placeholder="ENTER TICKER · AAPL"
                  autoFocus
                  className="flex-1 bg-transparent outline-none font-mono text-lg md:text-xl tracking-[0.15em] text-[var(--text-primary)] placeholder:text-[var(--text-muted)] py-4"
                />
                <button
                  type="submit"
                  disabled={!symbol.trim()}
                  className={cn(
                    'px-6 md:px-8 py-3.5 rounded-full bg-gold-gradient text-ink-900',
                    'font-mono text-xs uppercase tracking-[0.2em] font-bold',
                    'shadow-gold-glow hover:shadow-[0_0_60px_-5px_rgba(212,165,116,0.7)]',
                    'transition-all disabled:opacity-30 disabled:cursor-not-allowed',
                    'flex items-center gap-2'
                  )}
                >
                  <span className="hidden sm:inline">Analyze</span>
                  <ArrowRight size={14} />
                </button>
              </div>
            </div>

            {/* Quick pick chips */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.8, delay: 0.7 }}
              className="mt-8 flex flex-wrap justify-center items-center gap-2"
            >
              <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-[var(--text-muted)] mr-2">
                Or try —
              </span>
              {POPULAR.map((p, i) => (
                <motion.button
                  key={p.symbol}
                  onClick={() => handleQuickPick(p.symbol)}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.4, delay: 0.8 + i * 0.05 }}
                  whileHover={{ y: -2 }}
                  className="group px-3 py-1.5 rounded-full glass glass-hover font-mono text-xs transition-all"
                >
                  <span className="font-semibold text-[var(--text-primary)] group-hover:text-[var(--accent)]">
                    {p.symbol}
                  </span>
                  <span className="hidden md:inline text-[var(--text-muted)] ml-2 group-hover:text-[var(--text-secondary)]">
                    {p.name}
                  </span>
                </motion.button>
              ))}
            </motion.div>
          </motion.form>
        </section>

        {/* ════════════════════════════════════════════════
            STATS STRIP
        ════════════════════════════════════════════════ */}
        <motion.section
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.8 }}
          className="border-y border-[var(--border-subtle)] relative"
        >
          <div className="max-w-6xl mx-auto px-6 py-10">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-4">
              {STATS.map((s, i) => (
                <motion.div
                  key={s.label}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: i * 0.1 }}
                  className="text-center md:border-r md:border-[var(--border-subtle)] last:border-0"
                >
                  <div className="font-display text-4xl md:text-5xl font-light text-gold">
                    {s.value}
                  </div>
                  <div className="font-mono text-[10px] uppercase tracking-[0.25em] text-[var(--text-muted)] mt-2">
                    {s.label}
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </motion.section>

        {/* ════════════════════════════════════════════════
            FEATURES — 3 analysis engines
        ════════════════════════════════════════════════ */}
        <section className="max-w-6xl mx-auto px-6 py-24 md:py-32">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <div className="font-mono text-[10px] uppercase tracking-[0.3em] text-[var(--accent)] mb-3">
              ∕ Three Engines. One Terminal.
            </div>
            <h2 className="font-display text-4xl md:text-6xl font-light tracking-tight mb-6 leading-tight">
              Built for the
              <br />
              <em className="text-gold not-italic">discerning analyst.</em>
            </h2>
            <p className="text-[var(--text-secondary)] max-w-xl mx-auto text-balance">
              Three complementary engines, each crafted for a specific moment
              in the investment process.
            </p>
          </motion.div>

          <div className="grid md:grid-cols-3 gap-6">
            {FEATURES.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: i * 0.15 }}
              >
                <Link
                  href={f.href}
                  className="group block glass glass-hover rounded-3xl p-8 h-full relative overflow-hidden"
                >
                  {/* Top gold accent line */}
                  <div className="absolute top-0 left-0 right-0 h-px bg-gold-gradient opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

                  {/* Corner number */}
                  <div className="absolute top-6 right-6 font-mono text-[10px] uppercase tracking-[0.25em] text-[var(--text-muted)]">
                    0{i + 1}
                  </div>

                  {/* Icon */}
                  <div className="w-14 h-14 rounded-2xl bg-[var(--accent)]/10 text-[var(--accent)] flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-500">
                    <f.icon size={22} strokeWidth={1.5} />
                  </div>

                  {/* Badge */}
                  <div className="inline-block mb-4 px-2.5 py-1 rounded-full bg-[var(--bg-elevated)] border border-[var(--border-subtle)] font-mono text-[9px] uppercase tracking-[0.2em] text-[var(--text-secondary)]">
                    {f.badge}
                  </div>

                  {/* Title */}
                  <h3 className="font-display text-2xl mb-3 text-[var(--text-primary)] leading-tight">
                    {f.title}
                  </h3>

                  {/* Description */}
                  <p className="text-sm text-[var(--text-secondary)] leading-relaxed text-pretty mb-6">
                    {f.desc}
                  </p>

                  {/* Arrow */}
                  <div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.25em] text-[var(--accent)] group-hover:gap-4 transition-all">
                    Explore
                    <ArrowRight size={12} />
                  </div>
                </Link>
              </motion.div>
            ))}
          </div>
        </section>

        {/* ════════════════════════════════════════════════
            SHOWCASE — Visual preview
        ════════════════════════════════════════════════ */}
        <section className="max-w-6xl mx-auto px-6 pb-24 md:pb-32">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.8 }}
            className="glass rounded-3xl p-8 md:p-12 lg:p-16 relative overflow-hidden"
          >
            {/* Decorative grid in background */}
            <div className="absolute inset-0 grid-bg opacity-50 pointer-events-none" />
            <div className="absolute top-0 left-0 w-full h-px bg-gold-gradient opacity-40" />

            <div className="relative grid md:grid-cols-2 gap-12 items-center">
              <div>
                <div className="font-mono text-[10px] uppercase tracking-[0.3em] text-[var(--accent)] mb-4">
                  ∕ The Workflow
                </div>
                <h3 className="font-display text-4xl md:text-5xl font-light tracking-tight leading-tight mb-6">
                  From ticker to <em className="text-gold not-italic">thesis</em>,
                  <br />in under a minute.
                </h3>
                <div className="space-y-4">
                  {[
                    { n: '01', label: 'Enter ticker',    desc: 'Type or select from popular tickers' },
                    { n: '02', label: 'Explore overview', desc: '5Y trends, ratios, and quick insight' },
                    { n: '03', label: 'Model valuation',  desc: 'Adjust DCF assumptions in real-time' },
                    { n: '04', label: 'Generate AI report', desc: 'Full analyst memo in seconds' },
                  ].map((step) => (
                    <div key={step.n} className="flex gap-4 group">
                      <div className="font-mono text-[10px] text-[var(--accent)] pt-1 min-w-[24px]">
                        {step.n}
                      </div>
                      <div>
                        <div className="font-display text-lg text-[var(--text-primary)] leading-tight">
                          {step.label}
                        </div>
                        <div className="text-sm text-[var(--text-secondary)] mt-0.5">
                          {step.desc}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Right side: Visual mock */}
              <div className="relative">
                <div className="aspect-square glass rounded-2xl p-6 relative overflow-hidden">
                  <div className="absolute top-0 left-0 w-full h-px bg-gold-gradient opacity-60" />

                  <div className="flex items-center gap-2 mb-4">
                    <div className="w-2 h-2 rounded-full bg-[var(--negative)]" />
                    <div className="w-2 h-2 rounded-full bg-[var(--accent)]" />
                    <div className="w-2 h-2 rounded-full bg-[var(--positive)]" />
                    <span className="ml-auto font-mono text-[9px] uppercase tracking-widest text-[var(--text-muted)]">
                      AAPL.Preview
                    </span>
                  </div>

                  {/* Mini KPI stack */}
                  <div className="space-y-3">
                    <motion.div
                      initial={{ opacity: 0, x: -10 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: 0.2 }}
                      className="flex items-baseline justify-between py-2 border-b border-[var(--border-subtle)]"
                    >
                      <span className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">
                        Intrinsic Value
                      </span>
                      <span className="num-display text-2xl text-gold">$185.40</span>
                    </motion.div>
                    <motion.div
                      initial={{ opacity: 0, x: -10 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: 0.3 }}
                      className="flex items-baseline justify-between py-2 border-b border-[var(--border-subtle)]"
                    >
                      <span className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">
                        ROE (5Y Avg)
                      </span>
                      <span className="num-display text-2xl text-[var(--text-primary)]">164.2%</span>
                    </motion.div>
                    <motion.div
                      initial={{ opacity: 0, x: -10 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: 0.4 }}
                      className="flex items-baseline justify-between py-2 border-b border-[var(--border-subtle)]"
                    >
                      <span className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">
                        Free Cash Flow
                      </span>
                      <span className="num-display text-2xl text-[var(--text-primary)]">$108.8B</span>
                    </motion.div>
                    <motion.div
                      initial={{ opacity: 0, x: -10 }}
                      whileInView={{ opacity: 1, x: 0 }}
                      viewport={{ once: true }}
                      transition={{ delay: 0.5 }}
                      className="flex items-baseline justify-between py-2"
                    >
                      <span className="font-mono text-[10px] uppercase tracking-widest text-[var(--text-muted)]">
                        AI Verdict
                      </span>
                      <span className="font-display text-lg text-[var(--positive)]">Attractive</span>
                    </motion.div>
                  </div>

                  {/* Mini "chart" — just a decorative SVG */}
                  <svg viewBox="0 0 200 60" className="mt-6 w-full">
                    <defs>
                      <linearGradient id="lgrad" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="0%" stopColor="#d4a574" stopOpacity="0.4" />
                        <stop offset="100%" stopColor="#d4a574" stopOpacity="0" />
                      </linearGradient>
                    </defs>
                    <path
                      d="M 0,40 Q 40,35 60,30 T 120,25 T 200,10 L 200,60 L 0,60 Z"
                      fill="url(#lgrad)"
                    />
                    <path
                      d="M 0,40 Q 40,35 60,30 T 120,25 T 200,10"
                      stroke="#d4a574"
                      strokeWidth="2"
                      fill="none"
                    />
                  </svg>
                </div>
              </div>
            </div>
          </motion.div>
        </section>

        {/* ════════════════════════════════════════════════
            FINAL CTA
        ════════════════════════════════════════════════ */}
        <section className="max-w-4xl mx-auto px-6 pb-32 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <h3 className="font-display text-3xl md:text-5xl font-light tracking-tight mb-6 leading-tight">
              Begin with any ticker.
              <br />
              <em className="text-gold not-italic">It's that simple.</em>
            </h3>
            <button
              onClick={() => {
                const input = document.querySelector('input[type="text"]') as HTMLInputElement | null;
                input?.focus();
                window.scrollTo({ top: 0, behavior: 'smooth' });
              }}
              className="btn-luxe inline-flex items-center gap-3"
            >
              Search a ticker
              <ArrowRight size={12} />
            </button>
          </motion.div>
        </section>
      </main>

      <footer className="relative border-t border-[var(--border-subtle)]">
        <div className="max-w-6xl mx-auto px-6 py-8 flex flex-wrap items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="relative w-6 h-6 rounded-md bg-gold-gradient shadow-gold-glow overflow-hidden">
              <div className="absolute inset-0 flex items-center justify-center font-display font-bold text-ink-900 text-xs">
                L
              </div>
            </div>
            <span className="font-mono text-[10px] uppercase tracking-[0.25em] text-[var(--text-muted)]">
              Luxe Capital · Est. 2026
            </span>
          </div>
          <div className="font-mono text-[10px] text-[var(--text-muted)]">
            For research only · Not investment advice
          </div>
        </div>
      </footer>
    </div>
  );
}
